In [1]:
# ============================================================
# Install Required Libraries
# ============================================================

!pip install pandas openpyxl numpy -q

In [2]:
import pandas as pd
import numpy as np
import os

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [3]:
# Uncomment if your files are in Google Drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os

print(os.listdir("/content/drive/MyDrive"))

['ML-GenAI_RoadMap.docx', 'Colab Notebooks', 'archive (7)', 'archive (9)', 'vessel_model.h5', 'database']

In [5]:
print(os.listdir("/content/drive/MyDrive/database"))

['persons.xlsx', 'criminals.xlsx', 'officers.xlsx', 'evidence.xlsx', 'fir.xlsx', 'wanted.xlsx', 'cases.xlsx', 'charges.xlsx', 'arrests.xlsx', 'convictions.xlsx', 'warrants.xlsx', 'users.xlsx', 'merged_police_data.xlsx']

In [6]:
import pandas as pd

BASE_PATH = "/content/drive/MyDrive/database"

fir = pd.read_excel(f"{BASE_PATH}/fir.xlsx")
persons = pd.read_excel(f"{BASE_PATH}/persons.xlsx")
criminals = pd.read_excel(f"{BASE_PATH}/criminals.xlsx")
wanted = pd.read_excel(f"{BASE_PATH}/wanted.xlsx")
cases = pd.read_excel(f"{BASE_PATH}/cases.xlsx")
charges = pd.read_excel(f"{BASE_PATH}/charges.xlsx")
arrests = pd.read_excel(f"{BASE_PATH}/arrests.xlsx")
convictions = pd.read_excel(f"{BASE_PATH}/convictions.xlsx")
warrants = pd.read_excel(f"{BASE_PATH}/warrants.xlsx")
officers = pd.read_excel(f"{BASE_PATH}/officers.xlsx")
evidence = pd.read_excel(f"{BASE_PATH}/evidence.xlsx")
users = pd.read_excel(f"{BASE_PATH}/users.xlsx")

print("All Excel files loaded successfully!")

All Excel files loaded successfully!

In [7]:
datasets = {
    "FIR": fir,
    "Persons": persons,
    "Criminals": criminals,
    "Wanted": wanted,
    "Cases": cases,
    "Charges": charges,
    "Arrests": arrests,
    "Convictions": convictions,
    "Warrants": warrants,
    "Officers": officers,
    "Evidence": evidence,
    "Users": users
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

FIR: (50, 22)
Persons: (50, 12)
Criminals: (50, 13)
Wanted: (50, 8)
Cases: (50, 7)
Charges: (50, 6)
Arrests: (50, 6)
Convictions: (50, 6)
Warrants: (50, 6)
Officers: (50, 7)
Evidence: (50, 6)
Users: (50, 6)

In [8]:
for name, df in datasets.items():
    df.fillna("Unknown", inplace=True)

print("Missing Values Filled")

Missing Values Filled

In [9]:
merged = fir.merge(

    criminals,

    on="Criminal_ID",

    how="left"

)

In [10]:
merged = merged.merge(

    persons,

    on="Person_ID",

    how="left"

)

In [11]:
merged = merged.merge(

    officers,

    on="Officer_ID",

    how="left"

)

In [12]:
merged = merged.merge(

    cases,

    on="FIR_ID",

    how="left"

)

In [13]:
merged = merged.merge(

    charges,

    on=["FIR_ID","Criminal_ID"],

    how="left"

)

In [14]:
merged = merged.merge(

    arrests,

    on=["FIR_ID","Criminal_ID"],

    how="left"

)

In [15]:
merged = merged.merge(

    convictions,

    on="Criminal_ID",

    how="left"

)

In [16]:
merged = merged.merge(

    warrants,

    on="Criminal_ID",

    how="left"

)

In [17]:
merged = merged.merge(

    wanted,

    on="Criminal_ID",

    how="left"

)

In [18]:
merged = merged.merge(

    evidence,

    on="FIR_ID",

    how="left"

)

In [19]:
merged = merged.loc[:, ~merged.columns.duplicated()]

In [20]:
print(merged.shape)

merged.head()

(50, 87)

,FIR_ID,FIR_Number,Case_Number,FIR_Date,FIR_Time,Incident_Date,Incident_Time,Police_Station,District_x,Crime_Category,...,Last_Seen_Date,Last_Location,Reason,Issued_By,Active,Evidence_ID_y,Type_y,Description_y,File_Name,Uploaded_By
0,F001,TNFIR20260001,CASE001,2026-07-02,10:30,2026-07-02,09:45,T. Nagar Police Station,Chennai,Theft,...,2026-06-01,Chennai,Absconding after theft case,O001,Yes,E001,CCTV,CCTV collected during investigation,evidence_001.jpg,O001
1,F002,TNFIR20260002,CASE002,2026-07-03,10:30,2026-07-03,09:45,Peelamedu Police Station,Coimbatore,Cyber Crime,...,2026-06-03,Coimbatore,Online fraud investigation,O002,Yes,E002,Fingerprint,Fingerprint collected during investigation,evidence_002.jpg,O002
2,F003,TNFIR20260003,CASE003,2026-07-04,10:30,2026-07-04,09:45,S.S. Colony Police Station,Madurai,Robbery,...,2026-06-05,Madurai,Robbery case,O003,Yes,E003,DNA,DNA collected during investigation,evidence_003.jpg,O003
3,F004,TNFIR20260004,CASE004,2026-07-05,10:30,2026-07-05,09:45,Cantonment Police Station,Tiruchirappalli,Assault,...,2026-06-07,Salem,Assault case,O004,No,E004,Mobile Phone,Mobile Phone collected during investigation,evidence_004.jpg,O004
4,F005,TNFIR20260005,CASE005,2026-07-06,10:30,2026-07-06,09:45,Hasthampatti Police Station,Salem,Murder,...,2026-06-09,Tiruchirappalli,Murder investigation,O005,Yes,E005,Weapon,Weapon collected during investigation,evidence_005.jpg,O005

In [21]:
date_columns = merged.select_dtypes(include=["datetime64"]).columns

for col in date_columns:

    merged[col] = merged[col].astype(str)

In [22]:
for col in merged.columns:

    if merged[col].dtype == object:

        merged[col] = merged[col].astype(str).str.strip()

In [23]:
os.makedirs("processed", exist_ok=True)

merged.to_excel(

    "processed/merged_police_data.xlsx",

    index=False

)

print("Merged Dataset Saved Successfully")

Merged Dataset Saved Successfully

In [24]:
officers = officers.rename(columns={
    "Name": "Officer_Name",
    "Station": "Officer_Station",
    "District": "Officer_District",
    "Mobile": "Officer_Mobile",
    "Email": "Officer_Email"
})

persons = persons.rename(columns={
    "District": "Person_District",
    "Mobile": "Person_Mobile",
    "Email": "Person_Email"
})

cases = cases.rename(columns={
    "Status": "Case_Status"
})

warrants = warrants.rename(columns={
    "Status": "Warrant_Status",
    "Type": "Warrant_Type"
})

evidence = evidence.rename(columns={
    "Type": "Evidence_Type",
    "Description": "Evidence_Description",
    "Evidence_ID": "Evidence_Record_ID"
})

In [32]:
officers = officers.rename(columns={
    "Name": "Officer_Name",
    "Station": "Officer_Station",
    "District": "Officer_District",
    "Mobile": "Officer_Mobile",
    "Email": "Officer_Email"
})

persons = persons.rename(columns={
    "District": "Person_District",
    "Mobile": "Person_Mobile",
    "Email": "Person_Email"
})

cases = cases.rename(columns={
    "Status": "Case_Status"
})

warrants = warrants.rename(columns={
    "Status": "Warrant_Status",
    "Type": "Warrant_Type"
})

evidence = evidence.rename(columns={
    "Type": "Evidence_Type",
    "Description": "Evidence_Description",
    "Evidence_ID": "Evidence_Record_ID"
})

In [33]:
from google.colab import files

files.download("processed/merged_police_data.xlsx")

In [26]:
print("Rows :", merged.shape[0])

print("Columns :", merged.shape[1])

merged.sample(5)

Rows : 50
Columns : 87

,FIR_ID,FIR_Number,Case_Number,FIR_Date,FIR_Time,Incident_Date,Incident_Time,Police_Station,District_x,Crime_Category,...,Last_Seen_Date,Last_Location,Reason,Issued_By,Active,Evidence_ID_y,Type_y,Description_y,File_Name,Uploaded_By
31,F032,TNFIR20260032,CASE032,2026-07-05,10:30,2026-07-05,09:45,Peelamedu Police Station,Coimbatore,Cyber Crime,...,2026-08-03,Coimbatore,Fraud,O032,Yes,E032,Vehicle Photo,Vehicle Photo collected during investigation,evidence_032.jpg,O032
16,F017,TNFIR20260017,CASE017,2026-07-18,10:30,2026-07-18,09:45,Peelamedu Police Station,Coimbatore,Cyber Crime,...,2026-07-03,Tiruppur,Extortion,O017,Yes,E017,CCTV,CCTV collected during investigation,evidence_017.jpg,O017
49,F050,TNFIR20260050,CASE050,2026-07-23,10:30,2026-07-23,09:45,Hasthampatti Police Station,Salem,Murder,...,2026-09-08,Tirunelveli,Drug trafficking,O050,Yes,E050,Fingerprint,Fingerprint collected during investigation,evidence_050.jpg,O050
2,F003,TNFIR20260003,CASE003,2026-07-04,10:30,2026-07-04,09:45,S.S. Colony Police Station,Madurai,Robbery,...,2026-06-05,Madurai,Robbery case,O003,Yes,E003,DNA,DNA collected during investigation,evidence_003.jpg,O003
1,F002,TNFIR20260002,CASE002,2026-07-03,10:30,2026-07-03,09:45,Peelamedu Police Station,Coimbatore,Cyber Crime,...,2026-06-03,Coimbatore,Online fraud investigation,O002,Yes,E002,Fingerprint,Fingerprint collected during investigation,evidence_002.jpg,O002

In [27]:
fir[["Officer_ID"]].head(10)

  Officer_ID
0       O001
1       O002
2       O003
3       O004
4       O005
5       O006
6       O007
7       O008
8       O009
9       O010

In [28]:
merged[["Officer_ID", "Name"]].head(10)

  Officer_ID           Name
0       O001      R.Kumar 1
1       O002      S.Priya 2
2       O003  M.Saravanan 3
3       O004    D.Lakshmi 4
4       O005    V.Prakash 5
5       O006    K.Murugan 6
6       O007       A.Devi 7
7       O008     S.Ramesh 8
8       O009    P.Karthik 9
9       O010    N.Anitha 10

In [29]:
print(officers.columns.tolist())

['Officer_ID', 'Officer_Name', 'Rank', 'Officer_Station', 'Officer_District', 'Officer_Mobile', 'Officer_Email']

In [30]:
merged = merged.merge(
    officers,
    on="Officer_ID",
    how="left"
)

In [31]:
print(officers[officers["Officer_ID"] == "O001"])

  Officer_ID Officer_Name       Rank          Officer_Station  \
0       O001    R.Kumar 1  Inspector  T. Nagar Police Station

  Officer_District  Officer_Mobile         Officer_Email
0          Chennai      9700000001  o001@tnpolice.gov.in